### ISSUE TITLE
Add command-line option to repeat tests

### ISSUE THREAD

**Issue by vmalloc** [slash-testing/slash#140]

**Comment by ArielAzia** [comment]
Hi Rotem.
Any chance this will be implemented soon? 

thanks,
Ariel

**Comment by vmalloc** [comment]
There is a chance actually. One of the main blockers here is to clearly defined what's the expected behavior - do you want to repeat each test separately? all the tests as a whole?

**Comment by ArielAzia** [comment]
well, obviously these are two different things. I think the former is
straight forward and should work like a dumbed down version of
parameterize. about the latter, maybe only in the context of classes?
I mean, you can make a test-group context, and then invoke actions on that,
but I think that what the classes should be for? anyway, you're the boss. I
would be happy with a simple repeat per method.

btw thanks for this library, it is awesome.

**Comment by vmalloc** [comment]
No problem - I was asking about the specific use case you want. Something like --repeat=X which will repeat each test N times before proceeding. Does that sound satisfactory?

**Comment by ArielAzia** [comment]
oh, you are thinking of a flag for the command line? i thought more on
something like a decorator like parameterize. is that do-able as well?
we got some probabilistic behaviors of the test code we want routed out.

**Comment by vmalloc** [comment]
Oh, I didn't think about the decorator option at all... I think those should be separate issues...

In any case, the decorator option sounds much simpler to implement.

**Comment by vmalloc** [comment]
Opened #249 - and renamed the title of this issue to indicate command-line support...

**Comment by ArielAzia** [comment]
My teammate wants the support of the flag option like in py,test. I guess
any of these would be much appreciated

**Comment by vmalloc** [comment]
@ArielAzia FYI. Will be released (along with #249) in the upcoming release
