### ISSUE TITLE
winpdb debugger

### ISSUE THREAD

**Issue by eliadh** [slash-testing/slash#317]
hello.
can u add the winpdb (http://winpdb.org/) debugger to the debuggers Slash can recognize?
although last commit was way back at 2010, still very nice debugger..

thanks!

**Comment by vmalloc** [comment]
@eliadh I tried to find reference for invoking winpdb. Do you have any pointers?

**Comment by eliadh** [comment]
i used to call it directly in windows with the notation "winpdb
some_file.py"
Nice tutorial in  http://winpdb.org/tutorial/WinpdbTutorial.html

not much of a real documentation i'm afraid.

thanks.

**Comment by vmalloc** [comment]
It seems winpdb is a bit dead and in any case not very convenient for integration with slash...
