### ISSUE TITLE
[fixtures] implicit import of fixure doesn't work

### ISSUE THREAD

**Issue by eplaut** [slash-testing/slash#365]
Hi,

I have a fixture that used by another fixture, if I want to use the fixture I must import both of them, otherwise it raises 
```
E: UnknownFixtures: Fixture 'fix_a' not found!
2015-09-09 18:33:47 1781 slash.frontend.slash_run:slash_run:42 ERROR> Fixture 'fix_a' not found!
```

```python
"""content of fixtures.py"""
import slash

@slash.fixture
def fix_a():
    print('fixture a')

@slash.fixture
def fix_b(fix_a):
    print('fixture b')

"""content of test.py"""
import slash
from fixtures import fix_b

def test_fix(fix_b):
    pass
```

Adding `fix_a` to the import statement fix the problem.

Many thanks!
Eli

**Comment by vmalloc** [comment]
fixtures are only imported automatically when found in the same module or in a special file called `slashconf.py`. They are not scanned for in the entire repository.

**Comment by vmalloc** [comment]
See http://slash.readthedocs.org/en/master/fixtures.html#the-fixture-definition
